name:                aeson-goodies
version:             0.1.0.0
github:              "himura/aeson-goodies"
license:             BSD3
author:              "Takahiro HIMURA"
maintainer:          "taka@himura.jp"
copyright:           "2021 Takahiro HIMURA"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/aeson-goodies#readme>

dependencies:
- base >= 4.7 && < 5
- aeson >= 1.5
- attoparsec >= 0.13.2.2
- scientific >= 0.3.6.2
- text >= 0.11

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

tests:
  aeson-goodies-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aeson-goodies
    - tasty >=0.10 && <1.5
    - tasty-hunit >=0.9 && <0.11
    - tasty-quickcheck >=0.8 && <0.11
